#!/bin/bash
cd /home/hauntedw/Documents/Graphics-calculator/graphics-calculator/
clear
echo input "the keyword is 'math'"

read input

case $input in
	math)
		./main
		./plot
esac
clear


echo "run again? yes/no"
read again
case $again in
	yes)
		./run
esac
clear
